title: Csharp-datatables-parser
description: C# Serverside parser for the popuplar jQuery datatables plugin.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
