version: '2'
 
services:
  test-runner:
    build: 
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - mysql
      - mssql
  mysql:
    image: mysql
    container_name: dotnet-test-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Rea11ytrong_3"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "Rea11ytrong_3"
      MYSQL_DATABASE: "dotnettest"

  mssql:
    image: microsoft/mssql-server-linux
    container_name: dotnet-test-mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"   
      SA_PASSWORD: "Rea11ytrong_3"
